version: '3'
services:
  local_db:
    image: mysql:8.0
    container_name: local_db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root12345
      MYSQL_USER: local_user
      MYSQL_PASSWORD: root12345
      MYSQL_DATABASE: local_database
    volumes:
      - dbdata:/var/lib/mysql
    command: --local-infile=true

  local_test_db:
    image: mysql:8.0
    container_name: local_test_db
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root12345
      MYSQL_USER: local_user
      MYSQL_PASSWORD: root12345
      MYSQL_DATABASE: local_database
    volumes:
      - db_test_data:/var/lib/mysql
    command: --local-infile=true

volumes:
  dbdata:
    driver: local
  db_test_data:
    driver: local
